### ISSUE TITLE
Can't seem to find the [Content_Type].xml file for the CustomDuration solution?

### ISSUE THREAD

**Issue by jdburwood** [AndrewButenko/CustomDuration#6]
Hi Andrew,

We have used your previous solutions for our D365 environment before and they work great. We are trying to change some of the Duration values within the Duration dropdown and found your video and this solution here. But, I noticed when I try to download and import this solution, it is telling me that there is an error:

"The solution file is invalid. The compressed file must contain the following files at its root: solution.xml, customizations.xml, and [Content_Types].xml. Customization files exported from previous versions of Microsoft Dynamics 365 are not supported."

Noticed the [Content_Types].xml is missing from the CustomDuration solution? Thanks for any help Andrew!

**Comment by AndrewButenko** [comment]
Hello,
I haven't published solution for this control but I can do that if you're interested in it. I posted this control more for code-example purposes.
Andrew

**Comment by AndrewButenko** [comment]
Hello,
You can download solution file here - https://github.com/AndrewButenko/CustomDuration/releases/tag/1.0.0.0
Andrew

**Comment by jdburwood** [comment]
Wonderful - thank you Andrew!
